// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/starlink-detail/Sade.tsx": () => import("../components/mockups/starlink-detail/Sade.tsx"),
  "./components/mockups/starlink-detail/Zengin.tsx": () => import("../components/mockups/starlink-detail/Zengin.tsx"),
  "./components/mockups/email-alerts/EditorialSayisal.tsx": () => import("../components/mockups/email-alerts/EditorialSayisal.tsx"),
  "./components/mockups/email-alerts/LacivertOperasyon.tsx": () => import("../components/mockups/email-alerts/LacivertOperasyon.tsx"),
  "./components/mockups/email-alerts/RenkliDurumBanner.tsx": () => import("../components/mockups/email-alerts/RenkliDurumBanner.tsx")
};
