// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/customer-panel/Bridge.tsx": () => import("../components/mockups/customer-panel/Bridge.tsx"),
  "./components/mockups/customer-panel/Editorial.tsx": () => import("../components/mockups/customer-panel/Editorial.tsx"),
  "./components/mockups/customer-panel/Sade.tsx": () => import("../components/mockups/customer-panel/Sade.tsx"),
  "./components/mockups/customer-panel/WarmNordic.tsx": () => import("../components/mockups/customer-panel/WarmNordic.tsx"),
  "./components/mockups/dashboard-redesign/VariantA.tsx": () => import("../components/mockups/dashboard-redesign/VariantA.tsx"),
  "./components/mockups/dashboard-redesign/VariantB.tsx": () => import("../components/mockups/dashboard-redesign/VariantB.tsx"),
  "./components/mockups/dashboard-v2/VariantA.tsx": () => import("../components/mockups/dashboard-v2/VariantA.tsx"),
  "./components/mockups/dashboard-v2/VariantB.tsx": () => import("../components/mockups/dashboard-v2/VariantB.tsx"),
  "./components/mockups/kit-detail-v2/Norway.tsx": () => import("../components/mockups/kit-detail-v2/Norway.tsx"),
  "./components/mockups/kit-detail-v2/NorwayCustomer.tsx": () => import("../components/mockups/kit-detail-v2/NorwayCustomer.tsx"),
  "./components/mockups/kit-detail-v2/Satcom.tsx": () => import("../components/mockups/kit-detail-v2/Satcom.tsx"),
  "./components/mockups/kit-detail-v2/SatcomCustomer.tsx": () => import("../components/mockups/kit-detail-v2/SatcomCustomer.tsx"),
  "./components/mockups/kit-detail-v2/Starlink.tsx": () => import("../components/mockups/kit-detail-v2/Starlink.tsx"),
  "./components/mockups/kit-detail-v2/StarlinkCustomer.tsx": () => import("../components/mockups/kit-detail-v2/StarlinkCustomer.tsx"),
  "./components/mockups/kits-redesign/VariantA.tsx": () => import("../components/mockups/kits-redesign/VariantA.tsx"),
  "./components/mockups/kits-redesign/VariantB.tsx": () => import("../components/mockups/kits-redesign/VariantB.tsx"),
  "./components/mockups/email-alerts/EditorialSayisal.tsx": () => import("../components/mockups/email-alerts/EditorialSayisal.tsx"),
  "./components/mockups/email-alerts/LacivertOperasyon.tsx": () => import("../components/mockups/email-alerts/LacivertOperasyon.tsx"),
  "./components/mockups/email-alerts/RenkliDurumBanner.tsx": () => import("../components/mockups/email-alerts/RenkliDurumBanner.tsx"),
  "./components/mockups/starlink-detail/Sade.tsx": () => import("../components/mockups/starlink-detail/Sade.tsx"),
  "./components/mockups/starlink-detail/Zengin.tsx": () => import("../components/mockups/starlink-detail/Zengin.tsx")
};
